#!/bin/sh
horsat  example2.1.hrs
horsat  example2.2.hrs
horsat  example3.1.hrs
horsat  example3.2.hrs
horsat  example3.3.hrs
horsat  example3.5.hrs
horsat  example3.6.hrs
horsat  example3.7.hrs
horsat  example5.2.hrs
horsat  exp2-5.hrs
horsat  exp2-5-wrong.hrs
#horsat  exp3-5.hrs
#horsat  exp4-5.hrs      
horsat  fibstring2.hrs 
horsat  file.hrs
horsat  filewrong.hrs
horsat  fileocamlc.hrs  
horsat  fileocamlc-wrong.hrs  
horsat  lock2.hrs       
horsat  order5.hrs
horsat  order5-2.hrs    
horsat  repeat-2.hrs    
horsat  twofiles.hrs
horsat  twofilesexn.hrs
horsat  mc91-2.hrs  





